"""Generate and validate an isolated, Modal-only Codex configuration."""

from __future__ import annotations

import copy
import json
import os
import re
import secrets
import shutil
import socket
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .paths import CODEX_HOME, PROJECT_ROOT, ensure_state_dirs


BASE_CONFIG = r'''# Generated by codex-modal. This home is isolated from the user's ~/.codex.
check_for_update_on_startup = false
approvals_reviewer = "user"
web_search = "disabled"

[analytics]
enabled = false

[feedback]
enabled = false

[otel]
exporter = "none"
metrics_exporter = "none"
trace_exporter = "none"
log_user_prompt = false

[memories]
generate_memories = false
use_memories = false

[agents]
enabled = false

[features]
apps = false
browser_use = false
browser_use_external = false
computer_use = false
fast_mode = false
guardian_approval = false
image_generation = false
in_app_browser = false
in_app_updates = false
memories = false
multi_agent = false
multi_agent_v2 = false
plugin_sharing = false
plugins = false
remote_compaction_v2 = false
remote_plugin = false
standalone_web_search = false
tool_suggest = false

[tools]
web_search = false

[apps._default]
enabled = false
approvals_reviewer = "user"

[model_providers.modal]
name = "Modal Endpoints (isolated)"
base_url = "https://inference.us-west.modal.direct/v1"
env_key = "MODAL_PROXY_TOKEN"
wire_api = "responses"
requires_openai_auth = false
supports_websockets = false
supports_standalone_web_search = false

[shell_environment_policy]
ignore_default_excludes = false

[shell_environment_policy.filters]
"MODAL_PROXY_TOKEN" = "exclude"
"MODAL_PROXY_TOKEN_ID" = "exclude"
"MODAL_PROXY_TOKEN_SECRET" = "exclude"
"MODAL_TOKEN_ID" = "exclude"
"MODAL_TOKEN_SECRET" = "exclude"
"HF_TOKEN" = "exclude"
"HUGGING_FACE_HUB_TOKEN" = "exclude"
"OPENAI_API_KEY" = "exclude"
"CODEX_API_KEY" = "exclude"
'''


@dataclass(frozen=True)
class ModelSettings:
    slug: str
    display_model: str
    context_window: int
    reasoning_effort: str
    reasoning_levels: tuple[str, ...]
    provider_base_url: str
    persist_history: bool


@dataclass
class RunConfiguration:
    codex_executable: str
    profile_name: str
    profile_path: Path
    catalog_path: Path
    settings: ModelSettings
    environment: dict[str, str]

    def command_prefix(
        self, *, strict: bool = True, include_profile: bool = True
    ) -> list[str]:
        arguments = [self.codex_executable]
        if include_profile:
            arguments.extend(["--profile", self.profile_name])
        if strict:
            arguments.append("--strict-config")
        arguments.extend(["--model", self.settings.slug])
        for key, value in guard_overrides(self.settings, self.catalog_path):
            arguments.extend(["-c", f"{key}={value}"])
        return arguments

    def clean_up(self) -> None:
        for path in (self.profile_path, self.catalog_path):
            try:
                path.unlink()
            except FileNotFoundError:
                pass


def toml_string(value: str | Path) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.{secrets.token_hex(4)}.tmp")
    temporary.write_text(content, encoding="utf-8", newline="\n")
    os.replace(temporary, path)


def find_codex() -> str:
    executable = shutil.which("codex")
    if not executable:
        raise RuntimeError("Codex CLI is not installed or is not on PATH.")
    return executable


def isolated_environment(proxy_token: str | None = None) -> dict[str, str]:
    environment = os.environ.copy()
    for key in list(environment):
        upper = key.upper()
        if upper in {
            "OPENAI_API_KEY",
            "OPENAI_BASE_URL",
            "OPENAI_ORG_ID",
            "OPENAI_ORGANIZATION",
            "CODEX_API_KEY",
            "CODEX_SQLITE_HOME",
            "MODAL_PROXY_TOKEN_ID",
            "MODAL_PROXY_TOKEN_SECRET",
            "MODAL_TOKEN_ID",
            "MODAL_TOKEN_SECRET",
            "HF_TOKEN",
            "HUGGING_FACE_HUB_TOKEN",
        }:
            environment.pop(key, None)
    environment["CODEX_HOME"] = str(CODEX_HOME)
    if proxy_token is None:
        environment.pop("MODAL_PROXY_TOKEN", None)
    else:
        environment["MODAL_PROXY_TOKEN"] = proxy_token
    return environment


def _run_json(
    arguments: list[str],
    *,
    environment: dict[str, str],
    cwd: Path = PROJECT_ROOT,
) -> dict[str, Any]:
    result = subprocess.run(
        arguments,
        cwd=cwd,
        env=environment,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=60,
        check=False,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(
            f"Codex rejected generated configuration (exit {result.returncode})"
            + (f": {detail}" if detail else ".")
        )
    try:
        document = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise RuntimeError("Codex returned invalid JSON while validating its model catalog.") from error
    if not isinstance(document, dict):
        raise RuntimeError("Codex returned an unexpected model-catalog shape.")
    return document


def _bundled_template(codex_executable: str, environment: dict[str, str]) -> dict[str, Any]:
    document = _run_json(
        [codex_executable, "debug", "models", "--bundled"],
        environment=environment,
    )
    models = document.get("models")
    if not isinstance(models, list) or not models:
        raise RuntimeError("The installed Codex CLI provided no bundled model metadata.")
    template = next(
        (model for model in models if isinstance(model, dict) and model.get("slug") == "gpt-5.5"),
        None,
    )
    if template is None:
        template = next((model for model in models if isinstance(model, dict)), None)
    if template is None:
        raise RuntimeError("The bundled Codex model catalog had no usable model entry.")
    return copy.deepcopy(template)


def _model_entry(template: dict[str, Any], settings: ModelSettings) -> dict[str, Any]:
    reasoning_entries = [
        {
            "effort": level,
            "description": f"Use {level} reasoning effort on the selected Hugging Face model",
        }
        for level in settings.reasoning_levels
    ]
    instructions = str(template.get("base_instructions") or "")
    identity = (
        f"You are Codex, powered only by {settings.display_model} through a Modal endpoint."
    )
    if instructions:
        instructions = re.sub(r"\AYou are Codex,[^\r\n]*", identity, instructions)
    else:
        instructions = identity
    instructions += (
        "\n\nUse the standard tools supplied by Codex. Use the apply_patch tool for file edits."
    )

    template.update(
        {
            "slug": settings.slug,
            "display_name": f"Modal: {settings.display_model}",
            "description": "Hugging Face model served by a Modal managed endpoint",
            "default_reasoning_level": settings.reasoning_effort,
            "supported_reasoning_levels": reasoning_entries,
            "shell_type": "shell_command",
            "visibility": "list",
            "supported_in_api": True,
            "priority": 0,
            "base_instructions": instructions,
            "apply_patch_tool_type": "freeform",
            "supports_parallel_tool_calls": True,
            "supports_reasoning_summaries": True,
            "default_reasoning_summary": "none",
            "reasoning_summary_format": "none",
            "support_verbosity": False,
            "supports_search_tool": False,
            "supports_image_detail_original": False,
            "input_modalities": ["text"],
            "context_window": settings.context_window,
            "max_context_window": settings.context_window,
            "effective_context_window_percent": 95,
            "prefer_websockets": False,
            "use_responses_lite": False,
            "service_tiers": [],
            "additional_speed_tiers": [],
        }
    )
    for property_name in (
        "availability_nux",
        "upgrade",
        "minimal_client_version",
        "default_verbosity",
        "web_search_tool_type",
        "tool_mode",
        "available_in_plans",
        "comp_hash",
        "policy_template",
    ):
        template.pop(property_name, None)
    return template


def _profile_text(settings: ModelSettings, catalog_path: Path, workspace: Path) -> str:
    compact_limit = max(8192, int(settings.context_window * 0.90))
    history = "save-all" if settings.persist_history else "none"
    return f'''# Ephemeral per-run layer generated by codex-modal.
model = {toml_string(settings.slug)}
review_model = {toml_string(settings.slug)}
model_provider = "modal"
model_catalog_json = {toml_string(catalog_path)}
model_context_window = {settings.context_window}
model_auto_compact_token_limit = {compact_limit}
model_reasoning_effort = {toml_string(settings.reasoning_effort)}
model_reasoning_summary = "none"
web_search = "disabled"
check_for_update_on_startup = false
approvals_reviewer = "user"

[history]
persistence = "{history}"

[memories]
generate_memories = false
use_memories = false

[agents]
enabled = false
default_subagent_model = {toml_string(settings.slug)}

[model_providers.modal]
name = "Modal Endpoints (isolated)"
base_url = {toml_string(settings.provider_base_url)}
env_key = "MODAL_PROXY_TOKEN"
env_key_instructions = "Run codex-modal setup or set MODAL_PROXY_TOKEN."
wire_api = "responses"
requires_openai_auth = false
supports_websockets = false
supports_standalone_web_search = false
request_max_retries = 4
stream_max_retries = 5
stream_idle_timeout_ms = 1800000

[projects.{toml_string(workspace)}]
trust_level = "trusted"
'''


def guard_overrides(
    settings: ModelSettings, catalog_path: Path
) -> list[tuple[str, str]]:
    """Highest-precedence guards, including settings a project config could override."""

    compact_limit = max(8192, int(settings.context_window * 0.90))
    history = "save-all" if settings.persist_history else "none"
    false_keys = (
        "analytics.enabled",
        "feedback.enabled",
        "memories.generate_memories",
        "memories.use_memories",
        "agents.enabled",
        "features.apps",
        "features.browser_use",
        "features.browser_use_external",
        "features.computer_use",
        "features.fast_mode",
        "features.guardian_approval",
        "features.image_generation",
        "features.in_app_browser",
        "features.in_app_updates",
        "features.memories",
        "features.multi_agent",
        "features.multi_agent_v2",
        "features.plugin_sharing",
        "features.plugins",
        "features.remote_compaction_v2",
        "features.remote_plugin",
        "features.standalone_web_search",
        "features.tool_suggest",
        "tools.web_search",
        "apps._default.enabled",
    )
    overrides: list[tuple[str, str]] = [
        ("model", toml_string(settings.slug)),
        ("review_model", toml_string(settings.slug)),
        ("model_provider", '"modal"'),
        ("model_catalog_json", toml_string(catalog_path)),
        ("model_context_window", str(settings.context_window)),
        ("model_auto_compact_token_limit", str(compact_limit)),
        ("model_reasoning_effort", toml_string(settings.reasoning_effort)),
        ("model_reasoning_summary", '"none"'),
        ("web_search", '"disabled"'),
        ("check_for_update_on_startup", "false"),
        ("approvals_reviewer", '"user"'),
        ("apps._default.approvals_reviewer", '"user"'),
        ("history.persistence", toml_string(history)),
        ("agents.default_subagent_model", toml_string(settings.slug)),
        ("otel.exporter", '"none"'),
        ("otel.metrics_exporter", '"none"'),
        ("otel.trace_exporter", '"none"'),
        ("otel.log_user_prompt", "false"),
    ]
    overrides.extend((key, "false") for key in false_keys)
    return overrides


def _strict_offline_probe(configuration: RunConfiguration) -> None:
    """Make strict parsing reach a guaranteed-local connection failure, never a model."""

    guard_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    guard_socket.bind(("127.0.0.1", 0))
    port = int(guard_socket.getsockname()[1])
    local_base = f"http://127.0.0.1:{port}/v1"
    probe_environment = configuration.environment.copy()
    probe_environment["MODAL_PROXY_TOKEN"] = "wk-offline-probe.ws-offline-probe"
    command = configuration.command_prefix() + [
        "-c",
        f"model_providers.modal.base_url={toml_string(local_base)}",
        "-c",
        "model_providers.modal.request_max_retries=0",
        "-c",
        "model_providers.modal.stream_max_retries=0",
        "exec",
        "--ephemeral",
        "--skip-git-repo-check",
        "--ignore-rules",
        "--json",
        "codex-modal offline strict configuration probe",
    ]
    try:
        result = subprocess.run(
            command,
            cwd=PROJECT_ROOT,
            env=probe_environment,
            stdin=subprocess.DEVNULL,
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=30,
            check=False,
        )
    finally:
        guard_socket.close()
    combined = f"{result.stderr}\n{result.stdout}"
    if local_base in combined and "error" in combined.lower():
        return
    detail = combined.strip()
    raise RuntimeError(
        "Codex strict-mode validation did not reach the expected closed localhost provider"
        + (f": {detail}" if detail else ".")
    )


def _validate(
    configuration: RunConfiguration, workspace: Path, *, validate_strict: bool
) -> None:
    catalog_document = _run_json(
        [
            configuration.codex_executable,
            "-c",
            f"model_catalog_json={toml_string(configuration.catalog_path)}",
            "debug",
            "models",
        ],
        environment=configuration.environment,
    )
    models = catalog_document.get("models")
    slugs = [
        str(model.get("slug"))
        for model in models or []
        if isinstance(model, dict) and model.get("slug")
    ]
    if slugs != [configuration.settings.slug]:
        raise RuntimeError(
            "Codex did not enforce the generated one-model catalog; loaded: "
            + (", ".join(slugs) if slugs else "<none>")
        )

    validation_prefix = configuration.command_prefix(strict=False)
    validation = subprocess.run(
        validation_prefix + ["debug", "prompt-input", "codex-modal configuration validation"],
        cwd=workspace,
        env=configuration.environment,
        text=True,
        encoding="utf-8",
        errors="replace",
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        timeout=60,
        check=False,
    )
    if validation.returncode != 0:
        detail = validation.stderr.strip()
        raise RuntimeError(
            "The installed Codex CLI rejected the generated Modal-only profile"
            + (f": {detail}" if detail else ".")
        )
    if validate_strict:
        _strict_offline_probe(configuration)


def _prune_old_ephemeral_files() -> None:
    import time

    threshold = time.time() - 24 * 60 * 60
    for pattern in ("modal_*.config.toml", "catalog-modal_*.json"):
        for path in CODEX_HOME.glob(pattern):
            try:
                if path.stat().st_mtime < threshold:
                    path.unlink()
            except OSError:
                pass


def prepare_run_configuration(
    settings: ModelSettings,
    *,
    workspace: Path,
    proxy_token: str | None,
    validate_strict: bool = True,
) -> RunConfiguration:
    ensure_state_dirs()
    _atomic_text(CODEX_HOME / "config.toml", BASE_CONFIG)
    _prune_old_ephemeral_files()
    codex_executable = find_codex()
    environment = isolated_environment(proxy_token)
    template = _bundled_template(codex_executable, environment)

    run_id = f"modal_{os.getpid()}_{secrets.token_hex(6)}"
    catalog_path = CODEX_HOME / f"catalog-{run_id}.json"
    profile_name = run_id
    profile_path = CODEX_HOME / f"{profile_name}.config.toml"
    catalog = {"models": [_model_entry(template, settings)]}
    _atomic_text(
        catalog_path,
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n",
    )
    _atomic_text(profile_path, _profile_text(settings, catalog_path, workspace))

    configuration = RunConfiguration(
        codex_executable=codex_executable,
        profile_name=profile_name,
        profile_path=profile_path,
        catalog_path=catalog_path,
        settings=settings,
        environment=environment,
    )
    try:
        _validate(configuration, workspace, validate_strict=validate_strict)
    except Exception:
        configuration.clean_up()
        raise
    return configuration
